baseurl: /physiotherapie-rosenau
exclude: ['README.md']
permalink: pretty

sass:
  sass_dir: /assets/_scss
  #style: compressed

gems:
  - octopress-autoprefixer 

exclude: [node_modules, gulpfile.js]
